# Generated by Django 5.2.6 on 2026-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_point_classes_and_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebatch',
            name='surveyor_names',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
