# Generated by Django 5.2.6 on 2026-05-11 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_imagebatch_surveyor_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('batch-specific', 'Batch-Specific Report'), ('trend-analysis', 'Trend Analysis Report'), ('location-comparison', 'Location Comparison Report'), ('biodiversity', 'Biodiversity Distribution Report'), ('custom', 'Custom Report')], max_length=30)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('csv', 'CSV Data'), ('html', 'HTML Page')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
