# Generated by Django 5.2.6 on 2026-08-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Optional avatar shown in the navbar and Settings page', null=True, upload_to='profile_photos/'),
        ),
    ]
