# Generated by Django 5.2.6 on 2026-09-19 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_recompute_hcc_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('coverage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coverage_class', models.CharField(blank=True, default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transects', to='accounts.imagebatch')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='batchimage',
            name='transect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.transect'),
        ),
    ]
